"use client";
import {useMemo} from 'react';
import {BarChart3,Package,CheckCheck,AlertTriangle,ArrowUpRight} from 'lucide-react';
type Shipment={carrier:string;status:string};
import {STAGES} from '@/lib/domain.mjs';

export function OperationDashboard({loads,onExplore}:{loads:Shipment[];onExplore:(unit:string,status:string)=>void}){
 const stats=useMemo(()=>{
  const units=new Map<string,{name:string;total:number;done:number;missing:number}>();

  for(const l of loads){const name=l.carrier.trim()||'Sem unidade';const key=name.toLocaleLowerCase('pt-BR');const u=units.get(key)||{name,total:0,done:0,missing:0};u.total++;if(l.status==='Concluído'){u.done++;}if(l.status==='Falta item')u.missing++;units.set(key,u);}
  const rows=[...units.values()];const ranked=(key:'done'|'missing')=>rows.filter(u=>u[key]>0).sort((a,b)=>b[key]-a[key]||a.name.localeCompare(b.name));
  return {units:rows.length,done:loads.filter(l=>l.status==='Concluído').length,missing:loads.filter(l=>l.status==='Falta item').length,attended:ranked('done'),shortages:ranked('missing')};
 },[loads]);
 function ranking(title:string,subtitle:string,rows:typeof stats.attended,metric:'done'|'missing',status:string){return <article className={'dashboard-panel rank-'+metric}><div className="dashboard-panel-heading"><div><h2>{title}</h2><p>{subtitle}</p></div><BarChart3 size={21}/></div>{rows.length?<ol className="unit-ranking">{rows.slice(0,6).map((u,i)=><li key={u.name}><button onClick={()=>onExplore(u.name,status)}><span className="rank-position">{String(i+1).padStart(2,'0')}</span><span className="rank-content"><span><b>{u.name}</b><strong>{u[metric]} <small>{u[metric]===1?"lote":"lotes"}</small></strong></span><span className="rank-track"><span style={{width:`${100*u[metric]/rows[0][metric]}%`}}/></span></span><ArrowUpRight size={17}/></button></li>)}</ol>:<div className="dashboard-empty">{metric==='done'?'Os lotes concluídos aparecerão aqui.':'Nenhuma falta de item em aberto.'}</div>}<p className="metric-footnote">Clique na unidade para ver os lotes correspondentes.</p></article>}
 return <section className="analytics"><div className="heading"><div><p>PACKEM / INTELIGÊNCIA OPERACIONAL</p><h1>Dashboard<span>.</span></h1><p>Visão consolidada dos {loads.length} lotes disponíveis · todas as unidades</p></div><span className="dashboard-period">Todo o período</span></div><section className="dashboard-metrics">
 {[{title:'Unidades atendidas',value:stats.attended.length,caption:`${stats.units} unidades cadastradas`,icon:BarChart3},{title:'Lotes concluídos',value:stats.done,caption:loads.length?`${Math.round(stats.done/loads.length*100)}% do total de lotes`:'Sem lotes cadastrados',icon:CheckCheck},{title:'Faltas em aberto',value:stats.missing,caption:`Em ${stats.shortages.length} unidades`,icon:AlertTriangle},{title:'Total de lotes',value:loads.length,caption:'Todas as situações',icon:Package}].map(m=><article key={m.title}><m.icon size={21}/><span>{m.title}</span><strong>{m.value}</strong><small>{m.caption}</small></article>)}
 </section><div className="dashboard-columns">{ranking('Unidades mais atendidas','Ranking por quantidade de lotes concluídos',stats.attended,'done','Concluído')}{ranking('Unidades com mais faltas','Lotes com falta de item ainda em aberto',stats.shortages,'missing','Falta item')}</div><article className="dashboard-panel distribution"><div className="dashboard-panel-heading"><div><h2>Como está a operação</h2><p>Distribuição atual dos lotes por situação</p></div></div><div className="distribution-bar">{STAGES.map((status,i)=>{const count=loads.filter(l=>l.status===status).length;return count?<span key={status} className={'segment-'+i} style={{flex:count}} title={`${status}: ${count}`}/>:null})}</div><div className="distribution-legend">{STAGES.map((status,i)=>{const count=loads.filter(l=>l.status===status).length;return <button key={status} onClick={()=>onExplore('',status)}><i className={'segment-'+i}/><span>{status}</span><b>{count}</b><small>{loads.length?Math.round(count/loads.length*100):0}</small></button>})}</div></article><p className="metric-footnote">Faltas representam a situação atual, não o histórico de ocorrências.</p></section>;
}

