"use client";
import {ChevronLeft,ChevronRight,CalendarDays} from "lucide-react";
import {addDays,dayKey,longDate,shortDate,weekStart} from "@/lib/shipment-calendar";
type Props={loads:{scheduled_at:string}[];week:string;selected:string;all:boolean;onSelect:(week:string,day:string,all?:boolean)=>void};
export function ShipmentWeek({loads,week,selected,all,onSelect}:Props){
 const today=dayKey(new Date());const labels=["Segunda","Terça","Quarta","Quinta","Sexta","Sábado","Domingo"];
 const counts=new Map<string,number>();for(const l of loads){const key=dayKey(l.scheduled_at);counts.set(key,(counts.get(key)||0)+1)}
 const days=Array.from({length:7},(_,i)=>addDays(week,i));const weekend=days.slice(5).some(d=>(counts.get(d)||0)>0||d===selected||d===today);
 const total=days.reduce((sum,d)=>sum+(counts.get(d)||0),0);
 return <section className="shipment-week" aria-label="Programação por dia"><div className="week-heading"><div><small><CalendarDays size={14}/> PROGRAMAÇÃO SEMANAL</small><h2>{shortDate(week)} a {shortDate(addDays(week,6))}<span> / {week.slice(0,4)}</span></h2></div><div className="week-navigation"><button type="button" aria-label="Semana anterior" onClick={()=>onSelect(addDays(week,-7),"")}><ChevronLeft size={17}/></button><button type="button" onClick={()=>onSelect(weekStart(today),today)}>Hoje</button><button type="button" aria-label="Próxima semana" onClick={()=>onSelect(addDays(week,7),"")}><ChevronRight size={17}/></button></div></div><div className="week-days" role="group" aria-label="Dias de embarque">{days.slice(0,weekend?7:5).map((day,i)=><button type="button" key={day} aria-pressed={!all&&selected===day} aria-label={`${labels[i]}, ${shortDate(day)}, ${counts.get(day)||0} lotes`} className={`${!all&&selected===day?"selected":""} ${day===today?"is-today":""}`} onClick={()=>onSelect(week,day)}><span>{labels[i]}{day===today&&<em>HOJE</em>}</span><strong>{shortDate(day)}</strong><small>{counts.get(day)||0} {(counts.get(day)||0)===1?"lote":"lotes"}</small></button>)}</div><div className="week-footer"><div><button type="button" aria-pressed={!all&&!selected} onClick={()=>onSelect(week,"")}>Semana inteira <b>{total}</b></button><button type="button" aria-pressed={all} onClick={()=>onSelect(week,"",true)}>Todos os embarques</button>{(counts.get("")||0)>0&&<button type="button" aria-pressed={selected==="undated"&&!all} onClick={()=>onSelect(week,"undated")}>Sem data <b>{counts.get("")}</b></button>}</div><p>{all?"Todas as datas":selected==="undated"?"Defina a data desses lotes na edição.":selected?longDate(selected):"Selecione um dia para acompanhar os embarques."}</p></div></section>
}
